### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by sphrak** [vadret/android#140]
#### Weather
- [ ] add diagram/graph support on percipitation -- [Example 1](https://lh3.googleusercontent.com/mW6qJM6o4gfU1Xyjyi8GQzGg7FpD-cpheHB2R2bv8Q8WFT31ph6R4-mYnHOog7_6OiI=w1853-h979)
- [ ] add viewpager to weather screen

#### Weather
- [ ] add tstm (thunder warning) popup to weather screen

#### Warnings
- [ ] Add warnings count to weather screen -- depends on #137 
- [ ] Add periodic refresh of warnings from krisinformation.se -- #137

#### Radar
- [ ] add information "i" to screen with a color description/legend popup -- #138
