### ISSUE TITLE
refactoring todo list

### ISSUE THREAD

**Issue by sphrak** [vadret/android#17]
* [ ] schedulers as constructor arg in usecases 
* [ ] use livedata in viewmodel to get config change survivability for free
* [ ] move errorhandling to viewmodel instead of in fragments

**Comment by sphrak** [comment]
dupelicate #93
